variable "vpc_a" {}
variable "vpc_b" {}
variable "vpc_a_cidr" {}
variable "vpc_b_cidr" {}
variable "vpc_a_public_rt" {}
variable "vpc_b_public_rt" {}
variable "vpc_a_private_rt" {}
variable "vpc_b_private_rt" {}
variable "peer_region" {}
